INSERT INTO election.party(name, parent_party)
VALUES
    ('Alliance for Green Socialism', 1),
    ('Alliance for Green Socialism - Save NHS', 1),
    ('Breakthrough Party', 2),
    ('Conservative Party', 3),
    ('Conservative Party Candidate', 3),
    ('Local Conservatives', 3),
    ('The Conservative Party Candidate', 3),
    ('Democrats and Veterans Party', 4),
    ('East Leeds Independents Party', 5),
    ('English Democrats', 6),
    ('The For Britain Movement', 7),
    ('Freedom Alliance. No Lockdowns. No Curfews.', 8),
    ('Freedom Alliance. Truth, Equality and Health.', 8),
    ('Garforth and Swillington Independents Party', 9),
    ('Garforth & Swillington Independents Party', 9),
    ('Green Party', 10),
    ('Green Party lead candidate', 10),
    ('Green Party second choice candidate', 10),
    ('Green Party third choice candidate', 10),
    ('Green Party - Save Our Green Space', 10),
    ('The Green Party', 10),
    ('The Green Party Candidate', 10),
    ('Green Party Candidate', 10),
    ('Green Party candidate', 10),
    ('Independent', 11),
    ('Labour Party', 12),
    ('Labour and Co-operative Party', 12),
    ('Liberal Democrats', 13),
    ('Liberal Democrat Party', 13),
    ('Morley Borough Independents', 14),
    ('Northern Independence Party - Nationalise Energy Companies', 15),
    ('Reform UK', 16),
    ('Save Our Beeston & Holbeck Independents', 17),
    ('Save Our Beeston and Holbeck Independents', 17),
    ('Social Democratic Party', 18),
    ('Socialist Alternative', 19),
    ('Trade Unionist and Socialist Coalition', 20),
    ('Trade Unionists and Socialists Against Cuts', 21),
    ('UK Independence Party', 22),
    ('UKIP', 22),
    ('UK Independence Party (UKIP)', 22),
    ('United Kingdom Independence Party (UKIP)', 22),
    ('United Kingdom Independence Party', 22),
    ('UKIP Make Brexit Happen', 22),
    ('Women`s Equality Party', 23),
    ('Women''s Equality Party', 23),
    ('Yorkshire Party', 24),
    ('The Yorkshire Party', 24);
