INSERT INTO election.parent_party(id, name)
OVERRIDING SYSTEM VALUE
VALUES
    (1, 'Alliance for Green Socialism'),
    (2, 'Breakthrough Party'),
    (3, 'Conservative Party'),
    (4, 'Democrats and Veterans Party'),
    (5, 'East Leeds Independents Party'),
    (6, 'English Democrats'),
    (7, 'The For Britain Movement'),
    (8, 'Freedom Alliance'),
    (9, 'Garforth and Swillington Independents Party'),
    (10, 'Green Party'),
    (11, 'Independent'),
    (12, 'Labour Party'),
    (13, 'Liberal Democrats'),
    (14, 'Morley Borough Independents'),
    (15, 'Northern Independence Party'),
    (16, 'Reform UK'),
    (17, 'Save Our Beeston and Holbeck Independents'),
    (18, 'Social Democratic Party'),
    (19, 'Socialist Alternative'),
    (20, 'Trade Unionist and Socialist Coalition'),
    (21, 'Trade Unionists and Socialists Against Cuts'),
    (22, 'UK Independence Party'),
    (23, 'Women''s Equality Party'),
    (24, 'Yorkshire Party');
