INSERT INTO electoral_unit.ward(name, constituency_id)
VALUES
    ('Adel & Wharfedale', 5),
    ('Alwoodley', 4),
    ('Ardsley & Robin Hood', 7),
    ('Armley', 6),
    ('Beeston & Holbeck', 2),
    ('Bramley & Stanningley', 6),
    ('Burmantofts & Richmond Hill', 2),
    ('Calverley & Farsley', 8),
    ('Chapel Allerton', 4),
    ('Cross Gates & Whinmoor', 3),
    ('Farnley & Wortley', 6),
    ('Garforth & Swillington', 1),
    ('Gipton & Harehills', 3),
    ('Guiseley & Rawdon', 8),
    ('Harewood', 1),
    ('Headingley & Hyde Park', 5),
    ('Horsforth', 8),
    ('Hunslet & Riverside', 2),
    ('Killingbeck & Seacroft', 3),
    ('Kippax & Methley', 1),
    ('Kirkstall', 6),
    ('Little London & Woodhouse', 2),
    ('Middleton Park', 2),
    ('Moortown', 4),
    ('Morley North', 7),
    ('Morley South', 7),
    ('Otley & Yeadon', 5),
    ('Pudsey', 8),
    ('Rothwell', 1),
    ('Roundhay', 4),
    ('Temple Newsam', 3),
    ('Weetwood', 5),
    ('Wetherby', 1);
