INSERT INTO election.party(name)
VALUES
    ('Alliance for Green Socialism'),
    ('Conservative Party'),
    ('Conservative Party Candidate'),
    ('Local Conservatives'),
    ('The Conservative Party Candidate'),
    ('Democrats and Veterans Party'),
    ('East Leeds Independents Party'),
    ('The For Britain Movement'),
    ('Freedom Alliance. Truth, Equality and Health.'),
    ('Garforth and Swillington Independents Party'),
    ('Green Party'),
    ('Green Party lead candidate'),
    ('Green Party second choice candidate'),
    ('Green Party third choice candidate'),
    ('Green Party - Save Our Green Space'),
    ('The Green Party'),
    ('The Green Party Candidate'),
    ('Green Party candidate'),
    ('Independent'),
    ('Labour Party'),
    ('Labour and Co-operative Party'),
    ('Liberal Democrats'),
    ('Liberal Democrat Party'),
    ('Morley Borough Independents'),
    ('Northern Independence Party - Nationalise Energy Companies'),
    ('Reform UK'),
    ('Save Our Beeston & Holbeck Independents'),
    ('Save Our Beeston and Holbeck Independents'),
    ('Social Democratic Party'),
    ('Trade Unionist and Socialist Coalition'),
    ('Trade Unionists and Socialists Against Cuts'),
    ('UK Independence Party (UKIP)'),
    ('Women`s Equality Party'),
    ('Yorkshire Party'),
    ('The Yorkshire Party');
