INSERT INTO electoral_unit.ward(name, constituency_id)
VALUES
    ('Adel and Wharfedale', 5),
    ('Alwoodley', 4),
    ('Ardsley and Robin Hood', 7),
    ('Armley', 6),
    ('Beeston and Holbeck', 2),
    ('Bramley and Stanningley', 6),
    ('Burmantofts and Richmond Hill', 2),
    ('Calverley and Farsley', 8),
    ('Chapel Allerton', 4),
    ('Cross Gates and Whinmoor', 3),
    ('Farnley and Wortley', 6),
    ('Garforth and Swillington', 1),
    ('Gipton and Harehills', 3),
    ('Guiseley and Rawdon', 8),
    ('Harewood', 1),
    ('Headingley and Hyde Park', 5),
    ('Horsforth', 8),
    ('Hunslet and Riverside', 2),
    ('Killingbeck and Seacroft', 3),
    ('Kippax and Methley', 1),
    ('Kirkstall', 6),
    ('Little London and Woodhouse', 2),
    ('Middleton Park', 2),
    ('Moortown', 4),
    ('Morley North', 7),
    ('Morley South', 7),
    ('Otley and Yeadon', 5),
    ('Pudsey', 8),
    ('Rothwell', 1),
    ('Roundhay', 4),
    ('Temple Newsam', 3),
    ('Weetwood', 5),
    ('Wetherby', 1);
