INSERT INTO election.party(name)
VALUES
    ('Alliance for Green Socialism'),
    ('Conservative Party'),
    ('Local Conservatives'),
    ('The Conservative Party Candidate'),
    ('Freedom Alliance. Truth, Equality and Health.'),
    ('Garforth and Swillington Independents Party'),
    ('Green Party'),
    ('Green Party - Save Our Green Space'),
    ('The Green Party'),
    ('Green Party candidate'),
    ('Independent'),
    ('Labour Party'),
    ('Labour and Co-operative Party'),
    ('Liberal Democrats'),
    ('Liberal Democrat Party'),
    ('Morley Borough Independents'),
    ('Northern Independence Party - Nationalise Energy Companies'),
    ('Reform UK'),
    ('Social Democratic Party'),
    ('Trade Unionist and Socialist Coalition'),
    ('Women`s Equality Party'),
    ('Yorkshire Party');
